package com.tripoin.web.view.page.dashboard;

public class JsonUtilChart {
	
	public static final String CHART_ANALISA_PEMESANAN = ""
			+ "{	"
			+ " chart: {"
			+ " 	type: 'area'"
			+ "	        },"
			+ " title: {"
			+ " 	text: 'Analisa Pemesanan',"
			+ " 	x: -20"
			+ "}, subtitle: {"
			+ "     text: '',"
			+ "   	x: -20"
			+ "   },"
			+ "      xAxis: {"
			+ "	            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',"
			+ "	                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']"
			+ "	        },"
			+ "	        yAxis: {"
			+ "	            title: {"
			+ "   text: 'jumlah pesanan'"
			+ "	            }"
			+ " },"
			+ "	        tooltip: {"
			+ " 			valueSuffix: '°C'"
			+ "	        },"
			+ "	        legend: {"
			+ "	            layout: 'vertical',"
			+ "	            align: 'right',"
			+ "	            verticalAlign: 'middle',"
			+ "	            borderWidth: 0"
			+ "	        },"
			+ "	        series: [{"
			+ "	            name: 'Order',"
			+ "	            color: '#e3ff00',"
			+ "	            data: [10, 15, 8,9, 17, 36, 10, 10, 20, 17, 18, 6]"
			+ "	        },{"
			+ "	            name: 'Success',"
			+ "	            color: '#90ED7D',"
			+ "	            data: [7, 8, 3, 5,10, 21, 6, 5, 11, 12, 9, 3]"
			+ "	        }, {"
			+ "	            name: 'Fail',"
			+ "	            color: '#434348',"
			+ "	            data: [3,7, 5, 4, 7, 15, 4, 5, 9, 5, 9, 3]"
			+ "	        } ]"
			+ "}";

	public static final String CHART_ANALISA_PRODUK =
			"{"
			+ "        chart: {"
			+ "            type: 'column'"
			+ "        },"
			+ "        title: {"
			+ "            text: 'Analisa produk'"
			+ "        },"
			+ "        subtitle: {"
			+ "            text: ''"
			+ "        },"
			+ "        xAxis: {"
			+ "            categories: ["
			+ "                'W1',"
			+ "                'W2',"
			+ "                'W3',"
			+ "                'W4',"
			+ "                'W5' "
			+ "           ],"
			+ "            crosshair: true"
			+ "        },"
			+ "        yAxis: {"
			+ "            min: 0,"
			+ "            title: {"
			+ "                text: 'jumlah produk' "
			+ "           }"
			+ "        },"
			+ "        tooltip: {"
			+ "            headerFormat: '<span style=\"font-size:10px\">{point.key}</span><table>',"
			+ "            pointFormat: '<tr><td style=\"color:{series.color};padding:0\">{series.name}: </td><td style=\"padding:0\"><b>{point.y:.1f} </b></td></tr>',"
			+ "                "
			+ "            footerFormat: '</table>',"
			+ "            shared: true,"
			+ "            useHTML: true"
			+ "        },"
			+ "        plotOptions: {"
			+ "            column: {"
			+ "                pointPadding: 0.2,"
			+ "                borderWidth: 0"
			+ "            }"
			+ "        },"
			+ "        series: [{"
			+ "            name: 'Total Produk',"
			+ "            data: [60, 80,75, 50, 90]"
			+ "        }, {"
			+ "            name: 'Produk Terjual',"
			+ "            data: [40, 40, 35, 30, 50]"
			+ ""
			+ "        }, {"
			+ "            name: 'Produk Belum Terjual',"
			+ "            data: [20, 40, 40, 20, 40]"
			+ ""
			+ "        }]"
			+ "    }";
	
	public static final String CHART_NERACA_PENJUALAN =
			"{"
			+ "		 title: {"
			+ "	            text: 'Neraca penjualan',"
			+ "	            x: -20 "
			+ "	        },"
			+ "	        subtitle: {"
			+ "	            text: '',"
			+ "	            x: -20"
			+ "	        },"
			+ "	        xAxis: {"
			+ "	            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',"
			+ "	                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']"
			+ "	        },"
			+ "	        yAxis: {"
			+ "	            title: {"
			+ "	                text: 'jumlah pendapatan ($)'"
			+ "	            }"
			+ "	        },"
			+ "	        tooltip: {"
			+ "	            valueSuffix: '°C'"
			+ "	        },"
			+ "	        legend: {"
			+ "	            layout: 'vertical',"
			+ "	            align: 'right',"
			+ "	            verticalAlign: 'middle',"
			+ "	            borderWidth: 0"
			+ "	        },"
			+ "	        series: [{"
			+ "	            name: 'Pendapatan',"
			+ "	            color: '#49ff00',"
			+ "	            data: [7, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]"
			+ "	        }, {"
			+ "	            name: 'Pengeluaran',"
			+ "	            color: '#ff0000',"
			+ "	            data: [4, 8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]"
			+ "	        }, {"
			+ "	            name: 'pendapatan bersih',"
			+ "	            color: '#e3ff00',"
			+ "	            data: [3, 6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]"
			+ ""
			+ "	        }]"
			+ "    }";
	
	public static final String CHART_BEP =
			"{"
			+ "       chart: {"
			+ "           type: 'column'"
			+ "        },"
			+ "        title: {"
			+ "            text: 'BEP analysis(Break Event Point)'"
			+ "        },"
			+ "        subtitle: {"
			+ "            text: ''"
			+ "        },"
			+ "        xAxis: {"
			+ "            categories: ["
			+ "'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',"
			+ "'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'"
			+ "            ],"
			+ "            crosshair: true"
			+ "        },"
			+ "        yAxis: {"
			+ "            min: 0,"
			+ "            title: {"
			+ "                text: 'product / target($)'"
			+ "            }"
			+ "        },"
			+ "        tooltip: {"
			+ "            headerFormat: '<span style=\"font-size:10px\">{point.key}</span><table>',"
			+ "            pointFormat: '<tr><td style=\"color:{series.color};padding:0\">{series.name}: </td><td style=\"padding:0\"><b>{point.y:.1f} </b></td></tr>',"
			+ "   "
			+ "            footerFormat: '</table>',"
			+ "            shared: true,"
			+ "            useHTML: true"
			+ "        },"
			+ "        plotOptions: {"
			+ "            column: {"
			+ "                pointPadding: 0.2,"
			+ "                borderWidth: 0"
			+ "            }"
			+ "        },"
			+ "        series: [{"
			+ "            name: 'Produk',"
			+ "            data: [60, 80,75, 50, 90,60, 80,75, 50, 90,70,50]"
			+ "        }]"
			+ "    }";
}
